### ISSUE TITLE
The binary release of rakubrew is not able to download anything from the internet.

### ISSUE THREAD

**Issue by gugod** [Raku/App-Rakubrew#10]
Hi,

I was trying the `rakubrew` binary from `https://rakubrew.org/macos/rakubrew` and found out that it cannot download anything from internet. Such as:

```
> rakubrew available
No backend configured for scheme https at App/Rakubrew/Download.pm line 133.

> rakubrew download 2020.01
Cannot download Rakudo on '2020.01': this backend does not exist.
```
I'm guessing something needs to be done to let `HTTP::Tinyish` correctly chose the right backend for https -- although I'm not sure what that would be.

- What's the output of `rakubrew rakubrew-version`?:

rakubrew v6 Build type: macos OS: darwin

- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):

env

- Where is rakubrew installed? (run `rakubrew home` to find out):

`~/.rakubrew`

**Comment by gugod** [comment]
I've applied this patch and it seems to work. Although I'm only testing with my own perl installation instead of the relocatble-perl brought by `build-macos.sh`.

```patch
> git diff ./release-stuff/build-macos.sh
diff --git a/release-stuff/build-macos.sh b/release-stuff/build-macos.sh
index de3c60b..d1805e7 100755
--- a/release-stuff/build-macos.sh
+++ b/release-stuff/build-macos.sh
@@ -55,5 +55,5 @@ cpanm --installdeps -n .
 cpanm --installdeps -n --cpanfile cpanfile.macos .

 # PAR package rakubrew
-pp -I lib -M App::Rakubrew::Shell::* -M IO::Socket::SSL -o rakubrew script/rakubrew
+pp -I lib -M App::Rakubrew:: -M HTTP::Tinyish:: -M IO::Socket::SSL -o rakubrew script/rakubrew
```

**Comment by patrickbkr** [comment]
@gugod Thank you for the time to look into this and even create a patch! I have pushed a respective commit. I'll try to get a release out this evening. I'd be grateful if you could then give the release a try to see if it actually fixes the issue on MacOS (I don't have access to a Mac to try it myself).

**Comment by patrickbkr** [comment]
Version 8 of rakubrew finally was released.
@gugod If you find the time, can you test whether this new release works on MacOS?

**Comment by gugod** [comment]
@patrickbkr 

Thanks :D

I just give it a try, the command `available` works, but the command `download` does not, and `build` command also does not work. It looks like they are also failing for the same reason. I'll spend some time to investigate what makes the difference.

Heres' the output of what I tried:

```
> rakubrew rakubrew-version
rakubrew v8 Build type: macos OS: darwin

> rakubrew available
Available Rakudo versions:
   2009-02
   2009-03
   2009-04
   2009-05
   2009-06
(...deleted)


> rakubrew download 2020.02.1 
Cannot download Rakudo on '2020.02.1': this backend does not exist.

> rakubrew download 2020.02  
Cannot download Rakudo on '2020.02': this backend does not exist.

> rakubrew build 2020.02.1
Cannot build Rakudo with backend '2020.02.1': this backend does not exist.
```

**Comment by patrickbkr** [comment]
@gugod: try `rakubrew download moar 2020.02.1` and `rakubrew build moar 2020.02.1`

You're not the first one doing that mistake. I think a warning message is in order.

**Comment by gugod** [comment]
@patrickbkr thanks for the correction.  I retried and realized there is a different issue. It's more just than not fully packing HTTP::Tinyish into the binary tarball. I'm guess this issue can be consider resolved. 👍 

I managed to hunt those error and submitted PR #11.  Please take a look. 🙇
