### ISSUE TITLE
Cannot install latest version of Moar on Windows

### ISSUE THREAD

**Issue by antoniogamiz** [Raku/App-Rakubrew#14]
- What's the output of rakubrew rakubrew-version?:
~~~
rakubrew v9 Build type: win OS: MSWin32
~~~
- Are you using rakubrew in env or in shim mode? (run rakubrew mode to find out):
`env`
- Where is rakubrew installed? (run rakubrew home to find out):
`C:/rakubrew`

If I run `rakubrew download`, I get the following error: 
~~~
Couldn't find a precomp release for OS: "win", architecture: "x86_64"
~~~

**Comment by patrickbkr** [comment]
That's interesting. The release is clearly there on rakudo.org. I'll have a look at this.

**Comment by antoniogamiz** [comment]
`rakubrew build moar 2020.06` works perfectly though.

**Comment by antoniogamiz** [comment]
Agh, it was because I forgot to run `rakubrew switch moar-2020.06` again. Maybe that should be made automatically when you only have one version installed.

**Comment by patrickbkr** [comment]
@antoniogamiz I think rakubrew should already do that! If there is no version active at the moment and you install one, rakubrew should already switch to that. That possibly didn't work in your case because of the failed download beforehand.
