### ISSUE TITLE
Problem installing from zsh

### ISSUE THREAD

**Issue by JJ** [Raku/App-Rakubrew#19]
I get this error

```
sh: 4: set: Illegal option -o pipefail
```

When I try to install using zsh. Perl version is 5.20. I'm running Ubuntu 20.04, which is apparently affected [by this](https://stackoverflow.com/questions/54055549/linux-ubuntu-set-illegal-option-o-pipefail)

**Comment by patrickbkr** [comment]
This was already fixed in [899c8c8e416](https://github.com/Raku/rakubrew.org/commit/899c8c8e416962b239a8aec5266f9f6b9b18122a), but is not yet published.
Both rakubrew and the website are waiting for an upload of new releases.
ping @rba

**Comment by patrickbkr** [comment]
We finally managed to update the website. So this can be closed now.
