### ISSUE TITLE
Cannot build Moar/Windows releases from (roughly) 2020.07 onwards

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#24]
After fresh installs of git, Strawberry Perl and rakubrew, the command `rakubrew build moar-blead` fails (seeing this on both Win7 and Win10), croaking on 'debugserver.c'.  This works:`rakubrew build moar-2020.06`, but this does not: `rakubrew build moar-2020.07`.   Working backwards from the 2020.07 release, I found the last commit I could compile was [15fae6d](https://github.com/rakudo/rakudo/commit/15fae6d4e190b662b66ec7136eee66be97fc4256) from July 16th.

The errors are always the same, here's a representative [compile log](https://gist.github.com/SqrtNegInf/d98d683b52c5837514abd04a8bc741a8#file-rakubrew-build-windows-txt). Ignoring the `printf` noise, the crucial errors seem to have to do with threads, I wonder if it's related to these NQP changes?

```
20200717 p6d [09:55] <Geth_> ¦ nqp: 127803247 set debugserver's thread name
20200717 p6d [09:55] <Geth_> ¦ nqp: 707f6ce70 Debugserver Protocol 1.2: add thread "name" field
20200717 p6d [09:55] <Geth_> ¦ nqp: 1d52655e2 decode threadname with utf8-c8
```

Stuck at this point. Are there some other libraries I need to update first?  Ultimately this may not really be a `rakubrew` issue, but wanted to check here first to make sure I'm not just being all thumbs with Windows...

- What's the output of `rakubrew rakubrew-version`?:
   rakubrew v9 Build type: win OS: MSWin32
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
    shim
- Where is rakubrew installed? (run `rakubrew home` to find out):  
    C:/rakubrew

**Comment by patrickbkr** [comment]
Thanks for reporting this! This looks like a bug in MoarVM itself. I have created [a respective ticket](https://github.com/MoarVM/MoarVM/issues/1345) linking to this one. I'm closing this one in favor of the other.
