### ISSUE TITLE
Hot to find the p6doc binary

### ISSUE THREAD

**Issue by anquegi** [Raku/App-Rakubrew#25]
- What's the output of `rakubrew rakubrew-version`?:

`rakubrew v9 Build type: macos OS: darwin`

- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out

Usually env, but I tried also with shim

- Where is rakubrew installed? (run `rakubrew home` to find out):
/Users/toni/.rakubrew

Thanks for this great raku version manager, recently I started to learn raku, and going inside to perl world. so maybe my question is inaccurate. 

Recently I installed the new stable version of raku:

```
❯ rakubrew list
  system
  moar-2020.07
* moar-2020.08.2
```

I installed zef `rakubrew build-zef` and linenoise `zef install Linenoise` and it worked well (the autocomplete feature), but now I installed the p6doc [following ](https://github.com/Raku/doc) but I cannot find the p6doc executable:
```

~ via ⬢ v12.4.0
❯ p6doc
zsh: command not found: p6doc

~ via ⬢ v12.4.0
❯ which raku
/Users/toni/.rakubrew/versions/moar-2020.08.2/install/bin/raku

~ via ⬢ v12.4.0
❯ ls /Users/toni/.rakubrew/versions/moar-2020.08.2/install/bin/
moar			perl6-debug-m		raku			rakudo-gdb-m
nqp			perl6-gdb-m		raku-debug		rakudo-lldb-m
nqp-m			perl6-lldb-m		rakudo			rakudo-m
perl6			perl6-m			rakudo-debug		rakudo-valgrind-m
perl6-debug		perl6-valgrind-m	rakudo-debug-m
```
so I cannot use p6doc

**Comment by patrickbkr** [comment]
Thanks for bringing this up!

I think the documentation tooling is in a large process of refactoring at the moment. As far as I understand the `p6doc` module does not provide a `p6doc` command line utility anymore. According to the [readme](https://github.com/Raku/doc#install-rakudoc) the new `rakudoc` utility is provided [only in a repo](https://github.com/raku/rakudoc) at the moment.

I hope this clears up the confusion a little. If not, please reopen.

@JJ Can you confirm the above is correct?

**Comment by JJ** [comment]
Essentially correct, yes
