### ISSUE TITLE
The release index is not updated - self-upgrade does not work

### ISSUE THREAD

**Issue by mendel** [Raku/App-Rakubrew#26]
It seems somehow new releases after v9 did not make it to the `/releases` dir of the website (or at least the release index JSON document is not updated):

> mendel@vger:\~$ curl -s https://rakubrew.org/releases | jq .latest
> 9
> mendel@vger:\~$ 

Since `rakubrew self-upgrade` relies on that index being up to date, self-upgrade from v9 does not work:
> mendel@vger:\~$ rakubrew rakubrew-version
> rakubrew v9 Build type: fatpack OS: linux
> mendel@vger:\~$ rakubrew self-upgrade 
> Rakubrew is up-to-date!
> mendel@vger:\~$

**Comment by patrickbkr** [comment]
The process of updating the website and uploading new releases is a manual process. The only person currently able to do the updates is *very* short on time. That's why those updates didn't happen yet. I'm sorry for that. :-(

**Comment by patrickbkr** [comment]
ping @rba

**Comment by patrickbkr** [comment]
We now managed to update the website to the latest release.
