### ISSUE TITLE
Doesn’t fail hard when git is not installed

### ISSUE THREAD

**Issue by sarna** [Raku/App-Rakubrew#28]
```
Can't exec "git": No such file or directory at /home/me/.rakubrew/bin/rakubrew line 681.
Use of uninitialized value $ver in concatenation (.) or string at /home/me/.rakubrew/bin/rakubrew line 861.
Downloading https://rakudo.org/dl/rakudo/rakudo-moar-2020.09-01-linux-x86_64.tar.gz
Extracting
Use of uninitialized value $ver in concatenation (.) or string at /home/me/.rakubrew/bin/rakubrew line 287.
Done, moar- installed
```
I would prefer it to ask me to install git instead of doing that.

Thanks for your hard work, getting Raku is really painless with Rakubrew otherwise :)

**Comment by patrickbkr** [comment]
Thanks for the report! I have just added a logic that checks for git and perl in respective places and notifies the user that the tools are missing for that function. The change will (hopefully) go live in rakubrew v14 soonish.
