### ISSUE TITLE
Failure on MacOS with downloaded version, but local build OK

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#3]
As distributed, rakubrew fails for older MacOS (10.11, 10.13) with the error:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: rakubrew
  Expected in: /usr/lib/libSystem.B.dylib
```

From what I read, the lack of backwards compatibility from 10.15 could be due to '-fstack-check' compiler switch being 'on' by default, but can't test this as I don't have access to even 10.14 (I do see that PAR::Packer targets 10.11 as minimum version, so maybe it's Perl itself that's the problem?)

The good news is that cloning the repository and building it locally works fine. For reference, here's how I did it, [Build-rakubrew.sh](https://gist.github.com/SqrtNegInf/4af680d63669a75c19360f45ad4677d5)

**Comment by patrickbkr** [comment]
Thanks for the report! I have been using a homebrew installed perl to create the package. That was probably a bad idea. I'll look for a different one and prepare a package with that.

**Comment by patrickbkr** [comment]
That close was not intended. The fix still needs to be tested.

**Comment by patrickbkr** [comment]
@SqrtNegInf I just released v4 with based on a different perl version. Can you give it a try?

**Comment by patrickbkr** [comment]
Fixed as stated [here](https://github.com/Raku/App-Rakubrew/issues/8#issuecomment-590511535).
