### ISSUE TITLE
rakubrew doesn't work well on raspberry pi 4

### ISSUE THREAD

**Issue by demanuel** [Raku/App-Rakubrew#30]
- What's the output of `rakubrew rakubrew-version`?: rakubrew v13 Build type: fatpack OS: linux
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out): shim
- Where is rakubrew installed? (run `rakubrew home` to find out): 

Issue:
```

demanuel@fry:~$ rakubrew available
Couldn't detect system architecture. Current arch is: aarch64-linux-gnu-thread-multi
demanuel@fry:~$

```

**Comment by patrickbkr** [comment]
Thanks for the report! I have just pushed a change that makes rakubrew detect `arm64` and `armhf`. This will go live in the upcoming rakubrew v14 (hopefully) soonish.
