### ISSUE TITLE
Alias 6.c to 2018.10

### ISSUE THREAD

**Issue by JJ** [Raku/App-Rakubrew#33]
[That release was the last one to implement *only* 6.c](https://github.com/rakudo/rakudo/releases/tag/2018.10). Starting with the next one, implementation of 6.d features was also included. What I propose is simply add a 6.c alias that would actually install 2018.10.

**Comment by patrickbkr** [comment]
Shouldn't we rather add a respective tag to the rakudo repository instead of special-casing that into rakubrew? (That's what drives the version list of rakubrew.)

**Comment by JJ** [comment]
Hum, maybe... I can do that easily.

The problem is also that, the way I understand it, that's not really *the
last* 6.c implementation. 6.c implementation has progressed into the newer
releases, with new or disambiguated features under the 6.d implementation.
So it's actually the last *6.c only* implementation, not really the last
6.c implementation. Let me raise the issue somewhere and see if it's not a
problem for anyone.

**Comment by vrurg** [comment]
I would disagree that we should use `6.c` name for 2018.10. It's certainly not the last 6.c and naming it so will confuse people. Moreover, I don't see why would we ever need a tag of this kind until 6.c is supported in current Rakudo releases. If anyone cares about 6.c most likely his code is using explicit `use v6.c;` and as such should work with any Rakudo version.

**Comment by patrickbkr** [comment]
Closing this as I think it's not a rakubrew issue.
