### ISSUE TITLE
`rakubrew build zef` warning, latest version 

### ISSUE THREAD

**Issue by JJ** [Raku/App-Rakubrew#35]
This is just a warning. It works apparently well:

```
Use of uninitialized value $zef_version in string ne at /home/jmerelo/.rakubrew/bin/rakubrew line 818.
Ya en 'master'
Tu rama está actualizada con 'origin/master'.
===> Testing: zef:ver<0.11.5>:auth<github:ugexe>:api<0>
```

- What's the output of `rakubrew rakubrew-version`?:

```
rakubrew v15 Build type: fatpack OS: linux
```
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
shim

- Where is rakubrew installed? (run `rakubrew home` to find out):

```
/home/jmerelo/.rakubrew
```

**Comment by patrickbkr** [comment]
Fixed in https://github.com/Raku/App-Rakubrew/commit/007a868ab5c78d8691f67bcfd9b8124b5d85ee56
