### ISSUE TITLE
Sources on rakubrew.org not updating

### ISSUE THREAD

**Issue by raydiak** [Raku/App-Rakubrew#36]
I'm don't know if this is something automated or if somebody just forgot to do it by hand for v16, but https://rakubrew.org/perl/rakubrew is not built from the current version of rakubrew, so you still get the errors which were fixed in 007a868ab5c78d8691f67bcfd9b8124b5d85ee56 when following the official installation instructions at the top of https://rakubrew.org/. And since https://rakubrew.org/releases isn't updated either, even self-upgrade leaves it at v15.

**Comment by patrickbkr** [comment]
It's a semi automatic process and we missed to update the servers. It's done now. Thanks for the nudge!
