### ISSUE TITLE
Use of unintialized value $zef_version

### ISSUE THREAD

**Issue by JJ** [Raku/App-Rakubrew#37]
This is just a warning:

```text
Use of uninitialized value $zef_version in string ne at /home/jmerelo/.rakubrew/bin/rakubrew line 818.
```

- What's the output of `rakubrew rakubrew-version`?:

rakubrew v15 Build type: fatpack OS: linux

- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):

shim

- Where is rakubrew installed? (run `rakubrew home` to find out):

/home/jmerelo/.rakubrew

**Comment by patrickbkr** [comment]
This is a duplicate of #35 and has been fixed in version 16. You should be able to fix this with `rakubrew self-upgrade`. Can you confirm this works?

**Comment by patrickbkr** [comment]
ping @JJ

**Comment by JJ** [comment]
Totally. Sorry.
