### ISSUE TITLE
rakubrew build zef does it all wrong

### ISSUE THREAD

**Issue by vrurg** [Raku/App-Rakubrew#38]
- What's the output of `rakubrew rakubrew-version`?: `rakubrew v16 Build type: fatpack OS: linux`
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out): shim
- Where is rakubrew installed? (run `rakubrew home` to find out): `$HOME/.rakubrew`

What rakubrew currently does when it installs zef is it, in fact, must not do:

- it pollutes `cwd` with a cloned `zef` dir which remains there after the command finishes
- an attempt to install zef again ends with an error message if there is still `zef` directory from the previous installation:

```
fatal: not a git repository (or any of the parent directories): .git
Failed running git checkout master && git pull -q at /home/vrurg/.rakubrew/bin/rakubrew line 811.
```

**Comment by vrurg** [comment]
I'd propose `rakubrew` to change two things:

- the path to clone zef sources into must reside either under `~/.rakubrew` or `$TMPDIR/<some randomized subdir>`
- if `.rakubrew` is the choice then any pre-existing `zef` directory must be wiped out first and clone take place into a pristine location

**Comment by patrickbkr** [comment]
The error message is a bit misleading. rakubrew doesn't actually try to clone zef into cwd. It does the clone in the version dir where zef should be installed to. So e.g. `~/.rakubrew/versions/moar-2021.06/zef`. The error was, that when that directory is already existing (happens when zef has already been installed in that version), then `git checkout master && git pull` was executed in `~/.rakubrew/versions/moar-2021.06/` instead of  `~/.rakubrew/versions/moar-2021.06/zef` resulting in the above error. That should be fixed in the just released v17. You should be able to update with `rakubrew self-upgrade`.

@vrurg Can you confirm that the error is fixed in v17?

**Comment by vrurg** [comment]
I'm afraid this is just part of the problem. It doesn't change the fact that for manually registered versions zef is cloned into the current directory. Here is what happens. I have to cloned Rakudo repos. One is my fork, where I do most of the work and from where I produce PRs. And the original repo, which I use for clean tests and bisects. Here is what is looks like with `rakubrew list`:

```
  build -> /home/vrurg/src/Raku/rakudo/install
* master -> /home/vrurg/src/Raku/rakudo-master/install
```

Apparently, they're not in _~/.rakubrew/versions_. And every time I nuke and rebuild from scratch when time comes to `rakubrew build zef` I get a fresh copy of zef directory in my cwd. So, I get a couple of zef clones spread around my home directory tree time after time. For example, this is the outcome of `find ~ -name 'zef' -type d`:

```
/home/vrurg/.rakubrew/versions/moar-2021.04/zef
/home/vrurg/.rakubrew/versions/moar-2020.11/zef
/home/vrurg/.rakubrew/versions/moar-2020.02.1/zef
/home/vrurg/.rakubrew/versions/moar-2020.06/zef
/home/vrurg/.rakubrew/versions/moar-2020.09/zef
/home/vrurg/.rakubrew/versions/moar-2021.02/zef
/home/vrurg/.rakubrew/versions/moar-2021.03/zef
/home/vrurg/.rakubrew/versions/moar-2020.12/zef
/home/vrurg/.rakubrew/versions/moar-2020.10/zef
/home/vrurg/src/Raku/raku-Vikna/zef
/home/vrurg/src/Raku/zef
```

BTW, I would even disagree it makes sense to keep zef clones under version directories. After all, they're all the same clone. Perhaps it'd make more sense to have one copy under _.rakubrew/repos_ or alike.

**Comment by patrickbkr** [comment]
Oh! I didn't have external versions on the radar. Yes, there really was more wrong. I have reproduced the problem and fixed it in v18 (v19 is just some cleanup stuff).
Can you check if it now finally works in v19?

**Comment by vrurg** [comment]
Looks great:

```
Cloning into '/home/vrurg/.rakubrew/repos/zef'...
```

And on the second run:

```
HEAD is now at 602c54f Bump version 0.11.7
Already on 'master'
Your branch is up to date with 'origin/master'.
```

That was fast, thank you!
