### ISSUE TITLE
misreport "installed"

### ISSUE THREAD

**Issue by ithgub** [Raku/App-Rakubrew#40]
This issue is a continuation to https://github.com/Raku/App-Rakubrew/issues/39

This time I intentionally left little available disk space and then:
```
> rakubrew download moar 2020.08.1
Downloading https://rakudo.org/dl/rakudo/rakudo-moar-2020.08.1-01-linux-x86_64.tar.gz
Extracting
tar: rakudo-2020.08.1/lib/libmoar.so: Wrote only 7680 of 10240 bytes
tar: rakudo-2020.08.1/include: Cannot mkdir: No space left on device
tar: rakudo-2020.08.1/include: Cannot mkdir: No space left on device
tar: rakudo-2020.08.1/include/libatomic_ops: Cannot mkdir: No such file or directory
tar: rakudo-2020.08.1/include: Cannot mkdir: No space left on device
tar: rakudo-2020.08.1/include/libatomic_ops/atomic_ops.h: Cannot open: No such file or directory

# output abbreviated

tar: rakudo-2020.08.1/bin: Cannot mkdir: No space left on device
tar: rakudo-2020.08.1/bin/rakudo-m: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
Done, moar-2020.08.1 installed
```

Please note `Done, moar-2020.08.1 installed` despite obvious failure. Exitcode was `0` either.
(The specific version `2020.08.1` does not matter. Just an example. Any other would do the same, I believe)

Going further:
```
> rakubrew download moar 2020.08.1
moar-2020.08.1 is already installed.
```
Please note `is already installed` whereas we know it failed in the midst of installation.
```
> rakubrew switch moar-2020.08.1
Switching to moar-2020.08.1
Invalid version found: moar-2020.08.1 at /opt/olve/rakubrew/bin/rakubrew line 2782.
```
Please note `Invalid version found`. The version itself is valid. It is the installation that is incomplete and thus invalid.

(Just for the completeness sake:)
```
> rakubrew switch moar-2021.06
Switching to moar-2021.06
> raku --version
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2021.06.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2021.06.
> rakubrew nuke moar-2020.08.1
Nuking moar-2020.08.1
```

Regarding https://github.com/Raku/App-Rakubrew/issues/39 I believe a bit different conditions had had place since there had not been similar output for `rakubrew download moar 2020.08.2` as was here for `rakubrew download moar 2020.08.1` — I wouldn't have missed even a short error message; furthermore my shell indicates non-0 exitcodes in red and it had kept silence. Sorry, can't tell verbatim — the terminal output has scrolled beyond history.

- What's the output of `rakubrew rakubrew-version`?:
`rakubrew v19 Build type: fatpack OS: linux`
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
`env`
- Where is rakubrew installed? (run `rakubrew home` to find out):
`/opt/olve/rakubrew`

**Comment by patrickbkr** [comment]
This should be fixed by https://github.com/Raku/App-Rakubrew/commit/fdb768a9335771869f8b823da63fe72774bd1531 which is included in the v20 release. If you want to try, just run `rakubrew self-upgrade` to update to the latest version.
If not, please reopen this ticket.
