### ISSUE TITLE
More extensive testing is needed

### ISSUE THREAD

**Issue by JJ** [Raku/App-Rakubrew#42]
Right now, just the barest testing is done, basically compiling and so on. This causes new features to break existing build automations, such as #41. A more extensive test suit, testing different use cases, would be needed. Since testing might imply actually building Raku, we should find a way to mock different situations, so I'm not saying this is trivial. But still, avoiding errors in most, or some, use cases should receive the attention it really needs.

**Comment by patrickbkr** [comment]
Thanks for the poke!

I don't see much of a problem in mocking a rakudo installation.

The problem that kept me from adding more testing to rakubrew up to now is the strong interconnection of rakubrew and its environment. Rakubrew can hook into the outer shell and modifies the PATH variable. It has funcionality depending on the CWD. It also works on Windows in PowerShell and CMD. How can I setup a containment in which rakubrew can modify its environment as it wishes, without messing with the testscripts environment, and also allowing me to introspect that environment?
