### ISSUE TITLE
Make tarball of executable available in releases

### ISSUE THREAD

**Issue by CIAvash** [Raku/App-Rakubrew#43]
Is it possible to create tarball of the (one big) executable file and the LICENSE file. With version in its name, and a signature file and/or checksums. And publish them in the GitHub releases?

It seems the releases are uploaded to the rakubrew.org server, but I am not able to access them, unless I'm missing something.

Thinking of creating a binary package for AUR.

**Comment by patrickbkr** [comment]
Hi! I can make sure the previous releases are also accessible on rakubrew.org. (I prefer not to depend on GitHub too much.)
May I ask: Is there a reason, you prefer to base the AUR package on the fat-packed script instead of on the CPAN releases?
The CPAN version behaves a little different in that it prevents `self-upgrade` from working. That might be preferable behavior for a distro package as well.

**Comment by CIAvash** [comment]
Just faster installation, I installed with `cpanm` and it took a while, I guess `--notest` can help. There is already [a package](https://aur.archlinux.org/packages/rakubrew/) for installing via perl packages and makefile, maybe that is faster, I don't know. I usually use binary packages to avoid building everything, though in this case it's not really a binary. A lot of people prefer to build packages themselves, maybe I would do the same if I had a faster computer, I guess :)

And I prefer to manage programs from OS's package manager whenever feasible.

It's not a big issue if it takes your time.

Also a question, where does the man page come from? From CPAN?

**Comment by patrickbkr** [comment]
Should be fixed. See https://rakubrew.org/releases

I think CPAN (unsure which piece of the stack) somehow auto generates a man page from the POD documentation in the module.

**Comment by CIAvash** [comment]
@patrickbkr Hi, the https://rakubrew.org/releases no longer shows the files paths and I get error 403 when I try to get https://rakubrew.org/files/26/perl/rakubrew for example.

**Comment by patrickbkr** [comment]
Seems like the server somehow fell back on an older version. I'll have a look in the evening.

**Comment by patrickbkr** [comment]
As I suspected, the server somehow fell back to an old version of the website. Fixed now.
