### ISSUE TITLE
MacOS build of jvm-2021.12 reports success, yet marked 'broken' and cannot switch to it

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#47]
### The Problem
Attempted to build with the command:

<tt>rakubrew build jvm-2021.12</tt>

Tail end of build log:
```
    Installed 13 core modules in 224.598 seconds!
+++ JVM BACKEND INSTALLED
+++ Installing JVM launcher
+++ Rakudo installed succesfully!

Rakudo has been built and installed.
Updating shims
Done, jvm-2021.12 built
```
But attempting to use the build fails: 
```
% rakubrew versions
system
BROKEN   jvm-2021.12
  moar-2021.12
* moar-blead

% rakubrew switch jvm-2021.12
Version jvm-2021.12 is broken. Refusing to switch to it.
```
However if I call it directly, it works fine
```
% ~/.rakubrew/versions/jvm-2021.12/install/bin/perl6-j -v
Welcome to Rakudo™ v2021.12.
Implementing the Raku® Programming Language v6.d.
Built on JVM.
% ~/.rakubrew/versions/jvm-2021.12/install/bin/perl6-j -e 'say 2**8'
256
```
### Work-arounds (not good,  good)

I wondered if the <tt>is_version_broken</tt> routine (<tt>VersionHandling.pm</tt>) was failing 
here for not finding a matching name, as per line 92, but copying <tt>perl6-j</tt> as <tt>perl6</tt> didn't help.

`for my $exec ('raku', 'raku.bat', 'raku.exe', 'perl6', 'perl6.bat', 'perl6.exe') {`

I was able to successfully  build jvm-2021.12 on my own with:

<tt>perl Configure.pl --gen-nqp --backends=jvm --prefix ~/raku/jvm-2021.12; make  install</tt>

Did a <tt>diff -r</tt> on the two directory trees, but nothing stood out as a potential problem.

### Environment

- What's the output of `rakubrew rakubrew-version`?:
<tt>rakubrew v26 Build type: macos OS: darwin</tt>

- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
shim

- Where is rakubrew installed? (run `rakubrew home` to find out):
<tt>/Users/dhoekman/.rakubrew</tt>

- Build options used
<tt>export JAVA_OPTS="-Xmx51200000000"</tt>

**Comment by patrickbkr** [comment]
This should be fixed by https://github.com/Raku/App-Rakubrew/commit/1553868483af480c1d1b083716163eb5f743c2d0 which went live with v27. Thanks for the report!
