### ISSUE TITLE
"unauthenticated git protocol no longer supported"

### ISSUE THREAD

**Issue by JJ** [Raku/App-Rakubrew#48]
- What's the output of `rakubrew rakubrew-version`?:

    rakubrew v27 Build type: fatpack OS: linux

- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out): *shim*

- Where is rakubrew installed? (run `rakubrew home` to find out): `~/.rakubrew`

I get this error when I try to build the latest Rakudo:

```
fatal: error remoto: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Failed running git fetch at /home/jmerelo/.rakubrew/bin/rakubrew line 742.
```

**Comment by JJ** [comment]
I think that the problem is that if you upgrade `rakubrew`, it's using the old URL, since it's just doing `git fetch`

**Comment by JJ** [comment]
Workaround is:

Goto `~/.rakubrew/versions/moar-2022.02` (it might be another one in your case) and

    emacs .edit/config

changing `git://` by `https://`. 

It would be nice, however to have either of these

* Warnings when versions over 25 (which is where the change is introduced, I think) are installed
* Check for the repo configuration and change accordingly ← this is preferred, of course.

**Comment by patrickbkr** [comment]
Good find! I hope to manage to have a look in the coming days.

**Comment by anquegi** [comment]
Thanks for this workaroud:
> Workaround is:
> 
> Goto `~/.rakubrew/versions/moar-2022.02` (it might be another one in your case) and
> 
> ```
> emacs .edit/config
> ```
> 
> changing `git://` by `https://`.
> 
> It would be nice, however to have either of these
> 
>     * Warnings when versions over 25 (which is where the change is introduced, I think) are installed
> 
>     * Check for the repo configuration and change accordingly ← this is preferred, of course.

For OSX and rakubrew installed with homebrew I did the change to this file:

` ~/.rakubrew/git_reference/rakudo/config`
 
```
  [remote "origin"]
-	url = ://github.com/rakudo/rakudo.git
+	url = https://github.com/rakudo/rakudo.git
```

**Comment by patrickbkr** [comment]
The fix will go live in v28 which I hope to release soonish.
