### ISSUE TITLE
HTTP::Tiny doesn't have method "new"

### ISSUE THREAD

**Issue by Coleoid** [Raku/App-Rakubrew#5]
Getting the same error for most commands I give to rakubrew:

```
code> rakubrew download
Can't locate object method "new" via package "HTTP::Tiny" (perhaps you forgot to load "HTTP::Tiny"?) at App/Rakubrew/Download.pm line 36.
```
I do have a modern perl installed, with HTTP::Tiny in scope:

```
code> perl -MHTTP::Tiny
print "yep";
^Z
yep
code>
```

**Comment by patrickbkr** [comment]
Thanks for your report!
This error was corrected in version 2. I suspect you have an earlier version installed.
As the `self-upgrade` command is also affected by this, you won't be able to fix this by upgrading.
What you need to do is delete the rakubrew executable (probably located in ~/.local/share/rakubrew/bin/rakubrew) and reinstall.
Can you try the above and tell if it worked?

**Comment by Coleoid** [comment]
Hi, Patrick!
I'm installing in PowerShell via the line given on rakubrew.org:
. {iwr -useb https://rakubrew.org/install-on-powershell.ps1 } | iex
...which I just re-executed on a new machine, and am getting the same issue.  This suggests the PowerShell install accesses an out-of-date rakubrew package.
In that vein, another bug you may already have fixed:
PS C:\Users\Jason\AppData\Local\rakubrew\bin> .\rakubrew.exe initLoad rakubrew automatically by adding
  perl C:\Users\Jason\AppData\Local\rakubrew\bin\rakubrew init PowerShell | Out-String | Invoke-Expression
to your PowerShell profile.This can be easily done using:
  Add-Content -Force -Path $PROFILE -Value 'perl C:\Users\Jason\AppData\Local\rakubrew\bin\rakubrew init PowerShell | Out-String | Invoke-Expression'

The initial "perl" in that command needs to be removed on both mentions of the command.

Thanks for getting back to me on this!
Jason.
    On Thursday, February 13, 2020, 02:03:21 AM EST, Patrick Böker <notifications@github.com> wrote:  
 
 
Thanks for your report!
This error was corrected in version 2. I suspect you have an earlier version installed.
As the self-upgrade command is also affected by this, you won't be able to fix this by upgrading.
What you need to do is delete the rakubrew executable (probably located in ~/.local/share/rakubrew/bin/rakubrew) and reinstall.
Can you try the above and tell if it worked?

**Comment by patrickbkr** [comment]
You were right with your diagnosis! The `install-on-powershell.ps1` script did actually download an old version. Deployment of the corrected script to the website will take some time. In the meantime you can use this command to install instead (delete your previous installation first):

    . {iwr -useb https://github.com/Raku/rakubrew.org/blob/master/public/install-on-powershell.ps1 } | iex

And as you guessed, the wrong install command has also [already been fixed](https://github.com/Raku/App-Rakubrew/commit/a3b9f06b18d293f218a5596c589be572bb6f3fdc). Thanks for the report anyways!

**Comment by Coleoid** [comment]
Thanks!
  That iwr | iex line didn't work offhand, it cascaded errors.  If you want it, I'll add an issue for that, but by default I won't, since you sent it to me as a quick stopgap.  I grabbed the install file manually from Github, saved it locally, ran it, and the install worked smoothly.
  I got the extra config line in place, opened a new shell, and got a new error.  :/  Progress, yay.  I'll start a new issue for that one.  Maybe HTTP::Tinyish isn't using my normal environment config somehow?

J.    On Friday, February 14, 2020, 08:33:43 AM EST, Patrick Böker <notifications@github.com> wrote:  
 
 
You were right with your diagnosis! The install-on-powershell.ps1 script did actually download an old version. Deployment of the corrected script to the website will take some time. In the meantime you can use this command to install instead (delete your previous installation first):
. {iwr -useb https://github.com/Raku/rakubrew.org/blob/master/public/install-on-powershell.ps1 } | iex

And as you guessed, the wrong install command has also already been fixed. Thanks for the report anyways!

**Comment by patrickbkr** [comment]
The erroring with the Powershell command is probably because I used the wrong URL. The URL in the command I pasted is the one to the Github page, not to the raw script. The website has been updated in the meantime, so the command on the website itself should work now.
