### ISSUE TITLE
Unable to build on Windows 11

### ISSUE THREAD

**Issue by sdondley** [Raku/App-Rakubrew#57]
- What's the output of `rakubrew rakubrew-version`?: rakubrew v29 Build type: win OS: MSWin32
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out): shim
- Where is rakubrew installed? (run `rakubrew home` to find out): c:\rakubrew\bin

I have windows 11 virtual machine running in Virtual Box. I successfully installed rakubrew, but when trying to build with `rakubrew build 2022.07` and `rakubrew build 2022.06`,  I get errors:

```
from <unknown>:1
(C:\rakubrew\versions\moar-2022.06\install\share\nqp\lib\nqp.moarvm:<entry>)
gmake: *** [Makefile:1210: blib\Perl6\BOOTSTRAP\v6c.moarvm] Error 1
Command failed (status 512): gmake
at C:/rakubrew/versions/moar-2022.06/3rdparty/nqp-configure/lib/NQP/Config.pm
line 34.
       NQP::Config::__ANON__("Command failed (status 512):
gmake\x{a}") called at
C:/rakubrew/versions/moar-2022.06/3rdparty/nqp-configure/lib/NQP/Config.pm
line 1502
       NQP::Config::system_or_die("gmake") called at Configure.pl line 121
Failed running perl.exe Configure.pl --backends=moar --gen-moar
--make-install  --git-cache-dir="C:\rakubrew\git_reference" at
C:\Users\sdond\AppData\Local\Temp\par-73646f6e64\cache-c01daf663180ad36a32787effe9a0e828833d462\inc\lib/App/Rakubrew/Build.pm
line 113.
Rakubrew failed with exitcode 2
At line:7 char:9
+         Throw "Rakubrew failed with exitcode $LASTEXITCODE"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : OperationStopped: (Rakubrew failed with
exitcode 2:String) [], RuntimeException
   + FullyQualifiedErrorId : Rakubrew failed with exitcode 2

PS C:\rakubrew\bin> open text
open : The term 'open' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ open text
+ ~~~~
   + CategoryInfo          : ObjectNotFound: (open:String) [],
CommandNotFoundException
   + FullyQualifiedErrorId : CommandNotFoundException

-- 
```

**Comment by sdondley** [comment]
Ok thanks. Will look into it when I get a chance. I'm not a windows guy so I'm pretty clueless on this. Never used powershell before.

**Comment by sdondley** [comment]
After my unsuccessful attempts with rakubrew yesterday, I installed a windows binary version of Raku which I think must have installed the necessary software components because I can now use rakubrew to build rake successfully.

**Comment by patrickbkr** [comment]
That doesn't sound right. Which version did you install? The MSI installer from rakudo.org? Did you do anything else from running the MSI?

Did you run `. C:\path\to\this\folder\scripts\set-env.ps1` in the shell (as the README of the installer recommends) before using rakubrew? Or did you use a "Developer Command line" or "Developer PowerShell"? If yes, then that's the reason it started working.

To make use of the MSVC compiler the shell needs to be tuned using some .bat files provided by MSVC. This can be done by using one of their provided "Developer Command line" or "Developer PowerShell" or by running the above mentioned script that is packaged with the Rakudo installer.

**Comment by sdondley** [comment]
Yes, I installed the binary using the download at https://rakudo.org/downloads under the "Windows" tab: https://rakudo.org/dl/rakudo/rakudo-moar-2022.07-01-win-x86_64-msvc.msi

I don't specifically recall running anything the modified set-env.ps1. I followed the install instructions for powershell here: https://rakubrew.org/?platform=win then did `rakubrew init` which had me run some other commands which I had trouble with because there was some permission problem which I eventually got ironed out.  I also ran a command to get into shim mode at some point. After doing all that I rakubrew still failed. 

Perhaps a restart of windows might have fixed it? I have no idea.

**Comment by sdondley** [comment]
I just tried again with a clean install of windows 11 and I'm getting similar results. I think I have this line:

`. "C:\rakubrew\bin\rakubrew.exe" init PowerShell | Out-String | Invoke-Expression`

in the `C:\rakubrew\bin> cd C:\Users\sdond\Documents\WindowsPowerShell\WindowsPowerShell` file.

The above line was inserted by following the instructions provided by `rakubrew init`:

```
PS C:\rakubrew\bin> ./rakubrew.exe init
Load rakubrew automatically in PowerShell by adding

  . "C:\rakubrew\bin\rakubrew.exe" init PowerShell | Out-String | Invoke-Expression

to your PowerShell profile. (Note the "." at the beginning!)
This can be easily done using:

  New-Item -Path (Split-Path $PROFILE) -ItemType "Directory" -Force
  Add-Content -Force -Path $PROFILE -Value '. "C:\rakubrew\bin\rakubrew.exe" init PowerShell | Out-String | Invoke-Expression'
```

Despite this, I still have these problems spit out to me:

```
PS C:\rakubrew\bin> rakubrew list
rakubrew : The term 'rakubrew' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ rakubrew list
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (rakubrew:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command rakubrew was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\rakubrew". See "get-help about_Command_Precedence" for more details.
PS C:\rakubrew\bin> .\rakubrew list
The shell hook required to run rakubrew in either 'env' mode or with the 'shell' command seems not to be installed.
Run 'rakubrew init' for installation instructions if you want to use those features,
or run 'rakubrew mode shim' to use 'shim' mode which doesn't require a shell hook.
```

**Comment by patrickbkr** [comment]
I guess this can be closed. Please reopen if I'm mistaken.
