### ISSUE TITLE
https://rakubrew.org/ returns a 500 Server Error

### ISSUE THREAD

**Issue by xtaran** [Raku/App-Rakubrew#62]
Hi,

not sure if this is the proper place to report, but https://rakubrew.org/ (as listed as homepage for this repo) returns a "500 Server Error" for myself (Debian GNU/Linux Unstable, Chromium 108.0.5359.94) as well as for a friend of mine on macOS 12.6.2 Monterey with Safari as well as Firefox.

Maybe this is also be the cause for #59?

**Comment by JJ** [comment]
Does not work for me either, although with a blank page.

**Comment by patrickbkr** [comment]
It's the webserver that just needs a kick. The site is a long time victim of https://github.com/rakudo/rakudo/issues/4236 and needs a restart from time to time. This is unrelated to #59, rakubrew, once installed, does not rely on rakubrew.org (except for `self-upgrade`) but relies on the rakudo.org/ files for `download`. Maybe I'll manage to give the website a kick in the evening.

**Comment by patrickbkr** [comment]
I debugged the related memory leak a bit more and found a workaround. This problem should be gone for good. Thanks everyone!
