### ISSUE TITLE
Cannot build 'moar-blead' with rakubrew v31

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#63]
After upgrading to the latest  version of rakubrew (in order  to follow the  master->main switch of rakudo), I get an error message about an out-of-date NQP:

`.rakubrew/versions/moar-blead/install/bin/nqp-m version 2022.12-10-gf7e399c47 is outdated, 2022.12-14-g3685c4798 expected. at /Users/dhoekman/.rakubrew/versions/moar-blead/3rdparty/nqp-configure/lib/NQP/Config.pm line 192.`

Same results on macos/Darwin and Ubuntu.

However `rakubrew triple` successfully  builds `moar-HEAD-HEAD-HEAD`.

This also brings up  the question:  Is there any functional difference between this version and 'blead'?

- What's the output of `rakubrew rakubrew-version`?:
   rakubrew v31 Build type: macos OS: darwin
   rakubrew v31 Build type: fatpack OS: linux
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
  shim
- Where is rakubrew installed? (run `rakubrew home` to find out):
  $HOME/.rakubrew

**Comment by vrurg** [comment]
Feels to me that NQP is still fetched from `master`.

**Comment by SqrtNegInf** [comment]
Fix appears to simply be changing master->main on line 2666 of `rakubrew`

`configure => "$PERL5 Configure.pl --backends=moar --gen-moar=main --gen-nqp=main --make-install",`

I can submit this as a PR (but this can all wait until  after Christmas)

**Comment by patrickbkr** [comment]
SqrtNegInf: This is fixed with v32. Thanks for the report and fix!
(You probably know that already, but just for reference: You can do `rakubrew self-upgrade` to upgrade to the latest version.)
