### ISSUE TITLE
triple fails with make 512 error

### ISSUE THREAD

**Issue by 2colours** [Raku/App-Rakubrew#65]
- What's the output of `rakubrew rakubrew-version`?: `rakubrew v32 Build type: fatpack OS: linux`
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out): `env`
- Where is rakubrew installed? (run `rakubrew home` to find out): `$HOME/.rakubrew`

While building Rakudo with `triple`, after successfully building NQP, a `make` system call is made inside `~/.rakubrew/versions/moar-HEAD-HEAD-HEAD/3rdparty/nqp-configure/lib/NQP` where there is no Makefile or anything. This terminates the whole installation process.

I know that storage can be a bottleneck on this machine but I still have like 700MB on the home mount (out of 5GB) so I suppose that shouldn't be the problem in this case.

Sidenote: the whole reason I needed to try this is that `rakubrew build` downright fails with "not a git directory" out of the blue. Something is really messed up with how things are put into place and I definitely have seen this working on the very same setup (built the RakuAST branch a couple of months ago).

**Comment by patrickbkr** [comment]
@vrurg Could this be related to your recent build system changes WRT RakuAST?

**Comment by vrurg** [comment]
@patrickbkr I don't know what and how `triple` does to answer your question. In first place I'd wonder why something happens inside `nqp-configure` in first place.

BTW, the most likely cause could be renaming of `master` to `main` in `nqp-configure` repo. But normally it is checked out by hash by `Configure.pl` and this change shouldn't affect builds.

**Comment by 2colours** [comment]
I don't know what has changed exactly but it did work now.

If any of you know what could have addressed the problem, the issue could be closed.

**Comment by patrickbkr** [comment]
Could it be that it (reproducibly) fails on the first run, but succeeds on the second one?

**Comment by 2colours** [comment]
I'm not set up to do "first runs" repeatedly. :) But it rather seems to me that this might be fixed. It succeeded on a different system as well, and when I reported the failure, pretty sure I've tried to run it 2-3 times.

**Comment by 2colours** [comment]
I'm inclined to close this issue as non-reproducible. Things were very much in motion around those days; unless something similar happens to someone else, it's probably just noise.
