### ISSUE TITLE
can we minimize banner from eval "$(...scripts/set-env.sh)" ?

### ISSUE THREAD

**Issue by melezhik** [Raku/App-Rakubrew#66]
Right now when a user evals rakudo set-env.sh they are given a welcome banner, it makes a sense for human interaction, however in CI scripts it produces a lengthy message. Can we have some option to make this message less verbose?

Thanks

**Comment by patrickbkr** [comment]
The `set-env.sh` is actually a script of the precompiled Rakudo packages offered on rakudo.org (which Rakubrew uses). So this isn't a Rakubrew, but rather a Rakudo bug. Anyways, the [README.md](https://github.com/rakudo/rakudo/blob/main/tools/build/binary-release/assets/Linux/README.md) file hints at a `--quiet` option that should do pretty much what you want.

**Comment by melezhik** [comment]
Thanks!

**Comment by melezhik** [comment]
Looks like this option supported in the latest Raku do version only , it gets ignored (verbose output still produced) for the older versions … is that right ?

**Comment by patrickbkr** [comment]
That's correct.
