### ISSUE TITLE
Feature request: switch to last version

### ISSUE THREAD

**Issue by 2colours** [Raku/App-Rakubrew#67]
I'm thinking of something like a LAST file next to the CURRENT file that could be used to do `rakubrew switch -` or something similar. Nothing groundbreaking but it would be very convenient.

I might do it later; didn't want to forget it, nor dive into it just now.

**Comment by patrickbkr** [comment]
This was a one time request with not too strong opinion. I'll close this. If this comes up again, I'll reconsider.
