### ISSUE TITLE
Cannot build 'moar-blead' with rakubrew v32

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#68]
### Problem

rakubrew (v32) was building  <tt>moar-blead</tt> properly up until Jan 11th (near the time of the  Unicode 15 upgrade) but then I started to get this error: (extracting what are hopefully the most relevant lines from build log)

```
error: pathspec 'main' did not match any file(s) known to git
Command failed (status 256): git checkout main
 at /Users/dhoekman/.rakubrew/versions/moar-blead/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.

Failed running perl Configure.pl --backends=moar --gen-moar=main --gen-nqp=main --make-install  --git-cache-dir="/Users/dhoekman/.rakubrew/git_reference" at /var/tmp/par-.../inc/lib/App/Rakubrew/Build.pm line 113.
```

But if I re-run  that command making the change <tt>--gen-moar=master</tt> the build then completes properly.  Same results (for both bug and fix) on macos/Darwin and Ubuntu. 

In contrast, there is no problem with <tt>rakubrew triple</tt>, it successfully builds <tt>moar-HEAD-HEAD-HEAD</tt>. 
Is there is there any functional difference between this version and 'blead'?

### Environment

What's the output of rakubrew rakubrew-version?:
    • rakubrew v32 Build type: macos OS: darwin
    • rakubrew v32 Build type: fatpack OS: linux
Are you using rakubrew in env or in shim mode? (run rakubrew mode to find out):
    • shim
Where is rakubrew installed? (run rakubrew home to find out):
    • $HOME/.rakubrew

**Comment by patrickbkr** [comment]
Thanks for the report! That's a bug introduced in version 32. I have just fixed it in version 33.
You should be able to upgrade via `rakubrew self-upgrade`.
Can you verify it now works for you?

**Comment by SqrtNegInf** [comment]
All good now, thanks for the quick work.
