### ISSUE TITLE
Error on MacOS

### ISSUE THREAD

**Issue by FCO** [Raku/App-Rakubrew#7]
fernando@MBP-de-Fernando  ~  curl https://rakubrew.org/install-on-macos.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1090  100  1090    0     0   1552      0 --:--:-- --:--:-- --:--:--  1550
Downloading rakubrew...
sh: line 24: [: /Users/fernando/Library/Application: binary operator expected
Installing rakubrew to /Users/fernando/Library/Application Support/.rakubrew ...

sh: line 41: /Users/fernando/Library/Application: No such file or directory

**Comment by patrickbkr** [comment]
Thanks for the report!
This was just fixed by @nbrown in [rakubrew.org #2](https://github.com/Raku/rakubrew.org/pull/2).
The fix is not yet deployed to the website, but that will happen in the next days.
