### ISSUE TITLE
ARM64 support is required for macos

### ISSUE THREAD

**Issue by vrurg** [Raku/App-Rakubrew#79]
`rakubrew` binary is currently x86_64 only. This is kind of OK from the perspective of Rosetta taking care of it. But then a problem comes along because `rakubrew build` results in MoarVM compiled as x86_64 too. Later, when a module with a native lib dependency gets installed and the lib turns out to be arm64 only, the installation fails.

I anticipate that a universal binary format would solve the problem. But this needs to be tested.

**Comment by patrickbkr** [comment]
There is an arm64 rakubrew. The issue is that the website for some unknown reason rolled back to an older state and currently doesn't serve the arm64 binaries. I'm on it.

**Comment by patrickbkr** [comment]
I have now reset the website to latest. Installing an ARM64 rakubrew should thus now work again. Since you already have a rakubrew running it's probably easiest to just download https://rakubrew.org/macos_arm/rakubrew manually and overwrite your executable with it.
